/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedTestRouteImport } from './routes/_protected/test'
import { Route as ProtectedNewRouteImport } from './routes/_protected/new'
import { Route as ProtectedEditorIdRouteImport } from './routes/_protected/editor.$id'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTestRoute = ProtectedTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedNewRoute = ProtectedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedEditorIdRoute = ProtectedEditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/new': typeof ProtectedNewRoute
  '/test': typeof ProtectedTestRoute
  '/': typeof ProtectedIndexRoute
  '/editor/$id': typeof ProtectedEditorIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/new': typeof ProtectedNewRoute
  '/test': typeof ProtectedTestRoute
  '/': typeof ProtectedIndexRoute
  '/editor/$id': typeof ProtectedEditorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/todos': typeof TodosRoute
  '/_protected/new': typeof ProtectedNewRoute
  '/_protected/test': typeof ProtectedTestRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/editor/$id': typeof ProtectedEditorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/todos' | '/new' | '/test' | '/' | '/editor/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/todos' | '/new' | '/test' | '/' | '/editor/$id'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/todos'
    | '/_protected/new'
    | '/_protected/test'
    | '/_protected/'
    | '/_protected/editor/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  TodosRoute: typeof TodosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/test': {
      id: '/_protected/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof ProtectedTestRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/new': {
      id: '/_protected/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof ProtectedNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/editor/$id': {
      id: '/_protected/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof ProtectedEditorIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedNewRoute: typeof ProtectedNewRoute
  ProtectedTestRoute: typeof ProtectedTestRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedEditorIdRoute: typeof ProtectedEditorIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedNewRoute: ProtectedNewRoute,
  ProtectedTestRoute: ProtectedTestRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedEditorIdRoute: ProtectedEditorIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  TodosRoute: TodosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
